services:
  postgres:
    image: postgres:17
    container_name: seat-management-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-seatmanagement}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - seat-management-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: seat-management-redis
    volumes:
      - redis-data:/data
    networks:
      - seat-management-network
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: arshadali15/seat-management-backend:1.0.2
    container_name: seat-management-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-seatmanagement}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_PROFILES_ACTIVE: docker
    networks:
      - seat-management-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    image: arshadali15/seat-management-ui:1.0.2
    container_name: seat-management-ui
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres-data:
  redis-data:

networks:
  seat-management-network:

  # .\mvnw.cmd clean package -DskipTests
  # docker build --platform linux/amd64,linux/arm64 -t seat-management-backend:1.0.2 .
  # docker tag seat-management-backend:1.0.2 arshadali15/seat-management-backend:1.0.2
  # docker login
  # docker push arshadali15/seat-management-backend:1.0.2

  # docker build --platform linux/amd64,linux/arm64 -t seat-management-ui:1.0.2 .
  # docker tag seat-management-ui:1.0.2 arshadali15/seat-management-ui:1.0.2
  # docker push arshadali15/seat-management-ui:1.0.2


  # docker buildx build --platform linux/amd64,linux/arm64 -t arshadali15/seat-management-ui:1.0.2 --push .
  # docker buildx build --platform linux/amd64,linux/arm64 -t arshadali15/seat-management-backend:1.0.2 --push .
